config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
  post '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'create_post_like'
  post '/posts/:post_id/comments', to: 'comments#create', as: 'create_post_comment'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index show create update destroy]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  # validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]

  # GET /users
  def index
    @users = User.all

    render json: @users
  end

  # GET /users/1
  def show
    render json: @user
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created, location: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # DELETE /users/1

  def destroy
    @user.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/views/users/index.html.erb
<div class="container text-center">
  <h1>List of All users</h1>
  <p>Number of users: <%= @users.length %></p>
  <div class="row justify-content-center">
    <% @users.each do |user| %>
      <div class="col-md-4 mb-3">
        <div class="card h-100">
          <img src=<%= user.photo %> class="card-img-top" alt="<%= user.name %>'s photo">
          <div class="card-body">
            <%= link_to user_path(user.id) do %>
              <h2 class="card-title"><%= user.name %></h2>
            <% end %>
            <p class="card-text">Number of posts: <%= user.posts_counter || 0 %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
    <img src=<%= @user.photo%> alt="<%= @user.name%>'s photo">
    <div>
        <h1> <%= @user.name%> </h1>
        <p> number of posts: <%= @user.posts_counter || 0  %></p>
    </div>
</div>
<div>
    <h2>Bio</h2>
    <p> <%= @user.bio%> </p>
</div>
<div>
    <a href="<%= @user.id %>/posts"><h1> Posts </h1></a>
    <div>
        <% @user.recent_posts.each do |post| %>
            <div>
                <h3>Post #<%= post.id %> <%= link_to user_post_path(@user.id, post.id) do %><%= post.title %></h3>
                <% end %>
                <p> <%= post.text %> </p>
                <p> Comments: <%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter%> </p>
            </div>
        <% end %>
    </div>
</div>
<a href="<%=@user.id%>/posts" class="button">See all posts</a>