config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
  post '/users/:user_id/posts/:id/likes', to: 'likes#create', as: 'create_post_like'
  post '/posts/:post_id/comments', to: 'comments#create', as: 'create_post_comment'

  namespace :api do
    namespace :v1 do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index show] do
          resources :comments, only: %i[index show create update destroy]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attribute :comments_counter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  # validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  after_destroy :update_post_counter

  private

  def update_post_counter
    author.update(posts_counter: author.posts.all.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[show update destroy]

  # GET /posts
  def index
    @posts = Post.all

    render json: @posts
  end

  # GET /posts/1
  def show
    render json: @post
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      render json: @post, status: :created, location: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @comment = Comment.new
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments
    @like = Like.new
  end

  def new
    @user = current_user
    @post = Post.new
    @post.comments_counter = 0
  end

  def create
    @user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path notice: 'Post created successfully'
    else
      render :new
    end
    return unless @post.errors.any?

    puts @post.errors.full_messages
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    if @post.destroy
      flash[:success] = 'Post deleted successfully.'
      redirect_to user_posts_path(current_user)
    else
      flash[:error] = 'Failed to delete post.'
      redirect_to @post
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="container my-4">
  <div class="row align-items-center">
    <div class="col-md-2">
      <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" class="rounded-circle img-fluid">
    </div>
    <div class="col-md-6">
      <h2><%= @user.name %></h2>
      <%= link_to "Add New Post", new_user_post_path(@user), class: "btn btn-primary" %>
    </div>
  </div>
  <hr>
  <div class="row">
    <% @user.posts.each do |post| %>
      <div class="col-md-12">
        <div class="card my-4">
          <div class="card-body">
            <a href="<%= user_post_path(@user, post) %>">
              <h3 class="card-title">Post #<%= post.id %> <%= post.title %></h3>
            </a>
            <p class="card-text"><%= post.text.split[0..80].join(" ") %></p>
            <span class="text-muted"><%= post.comments_counter %> Comments, <%= post.likes_counter %> Likes</span>
          </div>
          <% if post.most_recent_comments.any? %>
            <div class="card-footer">
              <% post.most_recent_comments.includes(:author).each do |comment| %>
                <div class="mb-2">
                  <span><%= comment.author.name %>:</span> <%= comment.text %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= button_to "Pagination", "#", class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container my-4">
  <h1 style="text-align: center">Write a new post</h1>

  <%= form_with model: @post, url: user_posts_path(user.id), class: "my-4" do |form| %>
    <div class="form-group">
      <%= form.label :title, "Title" %>
      <%= form.text_field :title, class: "form-control", placeholder: "Enter a title for your post" %>
    </div>

    <div class="form-group">
      <%= form.label :text, "Content" %>
      <%= form.text_area :text, class: "form-control", placeholder: "Write your post content here..." %>
    </div>

    <%= form.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container my-6 mx-auto" style="width: 100%">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title">Post #<%= @post.id%>: <%= @post.title%></h2>
          <p class="card-text"><%= @post.text%></p>
              <%= form_with model: @like, url: user_post_likes_path(1, @post), scope: :like, html: { class: "form-inline" } do |form| %>
                <%= form.submit "Like", class: "btn btn-primary btn-sm"%>
              <% end %>
          <p class="card-text"><small class="text-muted">Posted by <%= @post.author.name %> <%= time_ago_in_words(@post.created_at)%> ago</small></p>
        </div>
        <div class="card-footer">
          <div class="d-flex justify-content-between align-items-center">
            <div>
          
              <span class="ml-2"><%= @post.likes_counter || 0 %> Likes</span>
            </div>
           
          </div>
        </div>
      </div>
      <% @comments.includes(:author).each do |comment| %>
        <div class="card my-3">
          <div class="card-body">
           <div> 
              <span class ="counter"><%= @post.comments_counter || 0 %> Comments</span>
             
            </div>
            <p class="card-text"><%= comment.author.name %>: <%= comment.text %></p>
            <% if can?(:destroy, @comment) %>
             <button> click me</button>
              <%= button_to "Delete", user_post_comment_path(@comment), method: :delete, class: "btn btn-danger btn-sm" %>
            <% end %>
           
            <small class="text-muted">Comment created <%= time_ago_in_words(comment.created_at)%> ago</small>
          </div>
        </div>
      <% end %>
       <button class="btn btn-primary btn-sm ml-2" style="width: fit-content"><%= link_to "Add comment", new_user_post_comment_path(post_id: @post.id) %> </button>
    </div>
  </div>
</div>